# Copyright 2026 Kavita Jadhav / K11 Software Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -*- coding: utf-8 -*-
"""
agents/auto_remediation_agent.py
─────────────────────────────────
Agent 15 — AutoRemediationAgent

Analyses defects produced by Phase 2 agents, selects those that belong to
safe, deterministic defect classes, generates code patches via LLM, and
opens remediation pull requests via the GitHub MCP server.

Safe remediable defect classes
───────────────────────────────
  accessibility_violation   WCAG aria-label, role, alt-text gaps
  missing_docstring         Public function/class missing docstring
  unused_import             Unused import statement
  missing_type_hint         Public function parameter/return missing hint
  test_coverage_gap         Uncovered code path identified by coverage agent

All other defect classes are skipped — they are flagged for human review via
the standard HITL / Jira ticket path.
"""

from __future__ import annotations

import json
import logging
import textwrap
from dataclasses import dataclass, field
from typing import Final

from langchain_openai import ChatOpenAI

from agents.base import AgentResult, BaseQAAgent

logger = logging.getLogger(__name__)

# ── Remediable defect classes ─────────────────────────────────────────────────

SAFE_CLASSES: Final[frozenset[str]] = frozenset({
    "accessibility_violation",
    "missing_docstring",
    "unused_import",
    "missing_type_hint",
    "test_coverage_gap",
})

# Minimum confidence required to attempt auto-remediation
CONFIDENCE_THRESHOLD: Final[float] = 0.80


# ── Data models ───────────────────────────────────────────────────────────────

@dataclass
class RemediationPatch:
    """A single LLM-generated patch for one defect."""
    defect_id:     str
    defect_class:  str
    file_path:     str
    description:   str
    patch:         str        # unified diff format
    confidence:    float      # 0.0–1.0 LLM self-assessment
    skipped:       bool = False
    skip_reason:   str = ""


@dataclass
class RemediationResult:
    """Outcome of the full remediation pass for a pipeline run."""
    attempted:   int = 0
    skipped:     int = 0
    patches:     list[RemediationPatch] = field(default_factory=list)
    pr_url:      str = ""          # GitHub remediation PR URL
    pr_number:   int = 0           # GitHub remediation PR number
    branch_name: str = ""
    error:       str = ""

    @property
    def success(self) -> bool:
        return bool(self.pr_url) and not self.error


# ── Prompts ───────────────────────────────────────────────────────────────────

PATCH_SYSTEM = """\
You are an expert software engineer generating minimal, safe code patches.
You will receive a defect description and the relevant source code context.
Your task is to generate a unified diff patch that fixes ONLY the described issue.

Rules:
- Make the smallest possible change that fixes the defect.
- Do NOT change logic, restructure code, or add features.
- Output ONLY a valid unified diff. No explanations, no markdown fences.
- After the diff, on a new line output: CONFIDENCE: <float 0.0-1.0>
  where confidence reflects how certain you are the patch is correct and safe.
"""

PATCH_USER = """\
Defect class: {defect_class}
File: {file_path}
Defect description: {description}

Source context:
{context}

Generate the patch now.
"""

PR_BODY_TEMPLATE = """\
## Auto-Remediation PR

This pull request was automatically generated by the **K11tech Agentic AI QA System**
AutoRemediationAgent in response to defects detected on PR #{original_pr}.

### Defects Addressed

{defect_list}

### Safety Guarantees

- Only safe, deterministic defect classes were patched (accessibility, docstrings,
  unused imports, type hints, test coverage gaps).
- Each patch was generated with LLM confidence ≥ {threshold:.0%}.
- No business logic was modified.
- This PR must be reviewed and merged manually — it is not auto-merged.

### Original PR
#{original_pr} in `{repo}`

---
*Generated by K11tech Agentic AI QA System v{version} · AutoRemediationAgent*
"""


# ── Agent ─────────────────────────────────────────────────────────────────────

class AutoRemediationAgent(BaseQAAgent):
    """
    Agent 15 — generates and submits code patches for safe defect classes.

    Pipeline position: Phase 2.5 — runs after Phase 2 parallel agents have
    completed but before Phase 3 reporting, so remediation PRs can be
    referenced in the final report.
    """

    NAME = "auto_remediation_agent"
    TIMEOUT = 480   # patch generation can be slow for large files

    def __init__(self, mcp_clients=None, llm=None) -> None:
        super().__init__(mcp_clients)
        self._llm = llm or ChatOpenAI(model="gpt-4o", temperature=0)

    # ── Public entry point ────────────────────────────────────────────────────

    async def execute(self, state: dict, suite: dict) -> AgentResult:
        """
        Main execution:
        1. Filter defects to safe remediable classes.
        2. Generate LLM patches for each.
        3. Create a remediation branch + commit patches via GitHub MCP.
        4. Open a remediation PR.
        """
        defects: list[dict] = state.get("defects", [])
        repo:    str        = state.get("repo_name", "")
        pr_num:  int        = state.get("pr_number", 0)
        version: str        = state.get("pipeline_version", "2.0.0")

        remediable = self._filter_remediable(defects)
        result = RemediationResult()

        if not remediable:
            self._log.info("No remediable defects found — skipping.")
            return AgentResult(
                agent=self.NAME,
                suite_type="remediation",
                passed=0,
                failed=0,
                total_cases=len(defects),
                metadata={"skipped_reason": "no_remediable_defects"},
            )

        # Generate patches
        patches = []
        for defect in remediable:
            result.attempted += 1
            patch = await self._generate_patch(defect, repo)
            if patch.skipped:
                result.skipped += 1
                self._log.warning(
                    "Skipping %s: %s", defect.get("id", "?"), patch.skip_reason
                )
            else:
                patches.append(patch)

        result.patches = patches

        if not patches:
            return AgentResult(
                agent=self.NAME,
                suite_type="remediation",
                passed=0,
                failed=result.skipped,
                total_cases=result.attempted,
                metadata={"skipped_reason": "all_patches_below_confidence"},
            )

        # Commit patches and open PR via GitHub MCP
        try:
            branch = f"auto-remediation/pr-{pr_num}-{state['run_id'][:8]}"
            await self._create_branch(repo, branch, state.get("base_branch", "main"))
            await self._commit_patches(repo, branch, patches)
            pr_url, pr_number = await self._open_pr(
                repo=repo,
                branch=branch,
                base=state.get("base_branch", "main"),
                original_pr=pr_num,
                patches=patches,
                version=version,
            )
            result.pr_url     = pr_url
            result.pr_number  = pr_number
            result.branch_name = branch
        except Exception as exc:
            result.error = str(exc)
            self._log.exception("Failed to create remediation PR")

        return AgentResult(
            agent=self.NAME,
            suite_type="remediation",
            passed=len(patches),
            failed=result.skipped,
            total_cases=result.attempted,
            defects=[],          # remediation agent does not produce new defects
            metadata={
                "remediation_pr_url":    result.pr_url,
                "remediation_pr_number": result.pr_number,
                "branch":                result.branch_name,
                "patches_applied":       len(patches),
                "patches_skipped":       result.skipped,
                "error":                 result.error,
            },
        )

    # ── Private helpers ───────────────────────────────────────────────────────

    def _filter_remediable(self, defects: list[dict]) -> list[dict]:
        """Return only defects whose class is in SAFE_CLASSES."""
        return [
            d for d in defects
            if d.get("defect_class") in SAFE_CLASSES
        ]

    async def _generate_patch(self, defect: dict, repo: str) -> RemediationPatch:
        """Ask the LLM to generate a patch for a single defect."""
        file_path = defect.get("file_path", "")
        defect_class = defect.get("defect_class", "unknown")
        description = defect.get("description", "")
        defect_id = defect.get("id", "unknown")

        # Fetch source context via GitHub MCP
        try:
            context_resp = await self.call_mcp(
                "github", "get_file_content",
                {"repo": repo, "path": file_path},
            )
            context = context_resp.get("content", "")[:3000]   # limit tokens
        except Exception:
            context = defect.get("context", "")

        # Build prompt
        prompt = PATCH_USER.format(
            defect_class=defect_class,
            file_path=file_path,
            description=description,
            context=context,
        )

        try:
            response = await self._llm.ainvoke([
                {"role": "system", "content": PATCH_SYSTEM},
                {"role": "user",   "content": prompt},
            ])
            raw = response.content.strip()
        except Exception as exc:
            return RemediationPatch(
                defect_id=defect_id,
                defect_class=defect_class,
                file_path=file_path,
                description=description,
                patch="",
                confidence=0.0,
                skipped=True,
                skip_reason=f"LLM call failed: {exc}",
            )

        # Parse patch + confidence from LLM output
        patch_text, confidence = self._parse_llm_output(raw)

        if confidence < CONFIDENCE_THRESHOLD:
            return RemediationPatch(
                defect_id=defect_id,
                defect_class=defect_class,
                file_path=file_path,
                description=description,
                patch=patch_text,
                confidence=confidence,
                skipped=True,
                skip_reason=f"Confidence {confidence:.2f} below threshold {CONFIDENCE_THRESHOLD}",
            )

        return RemediationPatch(
            defect_id=defect_id,
            defect_class=defect_class,
            file_path=file_path,
            description=description,
            patch=patch_text,
            confidence=confidence,
        )

    @staticmethod
    def _parse_llm_output(raw: str) -> tuple[str, float]:
        """Split LLM output into (patch, confidence)."""
        confidence = 0.0
        lines = raw.splitlines()
        patch_lines = []
        for line in lines:
            if line.strip().upper().startswith("CONFIDENCE:"):
                try:
                    confidence = float(line.split(":", 1)[1].strip())
                except ValueError:
                    pass
            else:
                patch_lines.append(line)
        return "\n".join(patch_lines).strip(), confidence

    async def _create_branch(self, repo: str, branch: str, base: str) -> None:
        await self.call_mcp("github", "create_branch", {
            "repo":   repo,
            "branch": branch,
            "from":   base,
        })

    async def _commit_patches(
        self, repo: str, branch: str, patches: list[RemediationPatch]
    ) -> None:
        for patch in patches:
            await self.call_mcp("github", "apply_patch", {
                "repo":    repo,
                "branch":  branch,
                "patch":   patch.patch,
                "message": (
                    f"fix({patch.defect_class}): auto-remediate {patch.file_path}\n\n"
                    f"Defect: {patch.description[:120]}\n"
                    f"Confidence: {patch.confidence:.0%}\n"
                    f"Generated by AutoRemediationAgent"
                ),
            })

    async def _open_pr(
        self,
        *,
        repo: str,
        branch: str,
        base: str,
        original_pr: int,
        patches: list[RemediationPatch],
        version: str,
    ) -> tuple[str, int]:
        defect_list = "\n".join(
            f"- **{p.defect_class}** in `{p.file_path}` "
            f"(confidence {p.confidence:.0%}): {p.description[:80]}"
            for p in patches
        )
        body = PR_BODY_TEMPLATE.format(
            original_pr=original_pr,
            defect_list=defect_list,
            threshold=CONFIDENCE_THRESHOLD,
            repo=repo,
            version=version,
        )
        resp = await self.call_mcp("github", "create_pull_request", {
            "repo":  repo,
            "title": f"[Auto-Remediation] Fix {len(patches)} safe defect(s) from PR #{original_pr}",
            "body":  body,
            "head":  branch,
            "base":  base,
            "draft": False,
        })
        return resp.get("html_url", ""), resp.get("number", 0)
